name: Build Linux Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache de dependências
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install cx-Freeze pygame-ce

      - name: Validar dependências
        run: |
          python --version
          pip show cx-Freeze pygame-ce

      - name: Rodar Testes Automatizados
        run: python -m unittest discover

      - name: Build do executável
        run: python setup.py build_exe

      - name: Upload do artefato
        uses: actions/upload-artifact@v3
        with:
          name: pong-linux
          path: build/exe.linux-x86_64-3.10/
