name: Build Linux Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install cx-Freeze pygame-ce

      - name: Build do executável
        run: python setup.py build_exe

      - name: Upload do artefato
        uses: actions/upload-artifact@v3
        with:
          name: pong-linux
          path: build/exe.linux-x86_64-3.10/
